### ISSUE TITLE
Bug - v1.3.x Throws Errors when Used in React

### ISSUE THREAD

**Issue by TheGreatAxios** [preactjs/signals#350]
Overview
---
Began using v1.2.2 ~3 weeks ago and it worked whether using new Signal() or signal outside of react component, or when using useSignal() within a component. Started a new project and automatically picked up v1.3.1. As soon as I began implementing signals, the app immediately broke.

Packages (using remix.run + React)
---
Remix.run - 1.1.15
Node.js - v18.12.0

The error thrown is: 

```sh
throw new Error('Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for' + ' one of the following reasons:\n' + '1. You might have mismatching versions of React and the renderer (such as React DOM)\n' + '2. You might be breaking the Rules of Hooks\n' + '3. You might have more than one copy of React in the same app\n' + 'See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.');
          ^
Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
```

There are also some other things related to goroutines and esbuild errors that throw:

```sh
fatal error: all goroutines are asleep - deadlock!

goroutine 1 [chan receive]:
github.com/evanw/esbuild/internal/helpers.(*ThreadSafeWaitGroup).Wait(...)
        github.com/evanw/esbuild/internal/helpers/waitgroup.go:36
main.runService.func2()
        github.com/evanw/esbuild/cmd/esbuild/service.go:127 +0x59
main.runService(0x1)
        github.com/evanw/esbuild/cmd/esbuild/service.go:181 +0x530
main.main()
        github.com/evanw/esbuild/cmd/esbuild/main.go:228 +0x21c

goroutine 34 [chan receive]:
main.runService.func1()
        github.com/evanw/esbuild/cmd/esbuild/service.go:111 +0x3e
created by main.runService
        github.com/evanw/esbuild/cmd/esbuild/service.go:109 +0x1e5

goroutine 35 [chan receive]:
main.(*serviceType).sendRequest(0xc00010dd40, {0x14a91c0, 0xc001c692c0})
        github.com/evanw/esbuild/cmd/esbuild/service.go:210 +0x110
main.runService.func3()
        github.com/evanw/esbuild/cmd/esbuild/service.go:138 +0x39
created by main.runService
        github.com/evanw/esbuild/cmd/esbuild/service.go:135 +0x353
```

Temporary Solution
---
Rollback to v1.2.2.

**Comment by JacquesDoubell** [comment]
I'm also getting errors.  I got the above and also TypeError: Cannot read properties of undefined (reading 'next')

**Comment by XantreGodlike** [comment]
Please add reproduction

**Comment by TheGreatAxios** [comment]
@XantreGodlike to preproduce:

1. Create Remix App
```bash
npx create-remix@latest
```
2. Add @preact/signals-react

```bash
npm add @preact/signals-react
```

3. Add a signal in the application whether in or out of state and the app will just continue to break and throw errors. I tested the hook (useSignal) as well as creating them outside of state (this is what I am actually doing i.e new Signal(xxx) or signal<T>(xxx) and everything throws an error

**Comment by andrewiggins** [comment]
I'm working on fixes for this. More coming soon

**Comment by XantreGodlike** [comment]
btw there are issues with react-native #346 i will try to add good repro too
